version: '3'
services:
 

  dbos:
    image: mysql:5.7
    volumes:
    - my-sql-storage-new:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MY_SQL_USER: vimal
      MY_SQL_PASSWORD: redhat
      MY_SQL_DATABASE: mydb

  wpos:
    image: wordpress:5.1.1-php7.3-apache
    volumes:
    - wp-storage:/var/www/html
    restart: always
    depends_on:
      - dbos
    ports:
      - 9096:80
    environment:
      WORDPRESS_DB_HOST: dbos
      WORDPRESS_DB_USER: vimal
      WORDPRESS_DB_PASSWORD: redhat
      WORDPRESS_DB_NAME: mydb
   
volumes: 
  wp-storage:
  my-sql-storage-new:

